"""Add relation issues to states

Revision ID: 04ec85fc18d6
Revises: 8b0d6c2d4e5f
Create Date: 2019-09-28 16:41:24.158646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04ec85fc18d6'
down_revision = '8b0d6c2d4e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('status_id', sa.Integer()))
    op.create_foreign_key(None, 'issues', 'statuses', ['status_id'], ['id'])
    op.drop_column('issues', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('status', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_column('issues', 'status_id')
    # ### end Alembic commands ###
