"""Remove fake_column

Revision ID: 24acca22903b
Revises: e73fc220567d
Create Date: 2019-06-30 11:28:11.044213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24acca22903b'
down_revision = 'e73fc220567d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('issues', 'status',
               existing_type=sa.VARCHAR(length=128),
               server_default=None,
               existing_nullable=True)
    op.drop_column('issues', 'fake_filed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('fake_filed', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('issues', 'status',
               existing_type=sa.VARCHAR(length=128),
               server_default=sa.text("'0'::character varying"),
               existing_nullable=True)
    # ### end Alembic commands ###
