"""Add field to issue table

Revision ID: 8660caebc649
Revises: 44b331ef1380
Create Date: 2019-09-29 13:01:52.926024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8660caebc649'
down_revision = '44b331ef1380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('contractor_id', sa.Integer(), nullable=True))
    op.add_column('issues', sa.Column('management_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'management_id')
    op.drop_column('issues', 'contractor_id')
    # ### end Alembic commands ###
