"""Add status_id to issue_history table

Revision ID: a5f7bc71cef3
Revises: c03e4d3f027f
Create Date: 2019-09-28 23:05:16.844144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f7bc71cef3'
down_revision = 'c03e4d3f027f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue_history', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'issue_history', 'statuses', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issue_history', type_='foreignkey')
    op.drop_column('issue_history', 'status_id')
    # ### end Alembic commands ###
