"""Fix contractor field

Revision ID: d9a46055ee55
Revises: 3445245ca6ab
Create Date: 2019-06-30 13:50:15.403878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9a46055ee55'
down_revision = '3445245ca6ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('contractor', sa.String(length=256), nullable=True))
    op.drop_column('issues', 'constractor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('constractor', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('issues', 'contractor')
    # ### end Alembic commands ###
