openapi: 3.0.2
info:
  title: Ariadna API
  contact:
    name: Team One
    email: nifigator@gmail.com
  version: '1.0.0'

servers:
  - url: /api/v1.0

paths:
  /customer/{customer_id}:
    get:
      summary: Get customer Info
      operationId: app.dummy
      tags:
        - Customers
      parameters:
      - name: customer_id
        description: Customer unique identifier
        in: path
        required: true
        example: 12
        schema:
          type: integer
      responses:
        '200':
          description: Customer data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Customer:
      properties:
        name:
          type: string
          description: Customer name
          example: Ivan
        middlename:
          type: string
          description: Customer name
          example: Ivanovich
        surname:
          type: string
          description: Customer name
          example: Ivanov
        street:
          type: string
          description: Custoner street
          example: Markovskogo
        house:
          type: string
          description: Customer hosuse number
          example: 12a
        flat:
          type: integer
          description: Customer flat number
          example: 99
        phone:
          type: string
          description: Customer phone number
          example: +79991234567
        email:
          type: string
          description: Customer email
          example: user@mail.com

    Error:
      required:
        - code
        - message
      properties:
        code: 
          type: integer
          format: int32
        message:
          type: string

